version: '3.9'

networks:
  dev:

volumes:
  db_data:

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

  php:
    restart: unless-stopped
    container_name: php
    networks:
      - dev
    build:
      context: './.docker/php'
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - './:/var/www:delegated'
    depends_on:
      - db

  db:
    image: 'mariadb:latest'
    environment:
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: app
    networks:
      - dev
    volumes:
        - db_data:/var/lib/mysql
    ports:
        - '3306:3306'
